# Generated by Django 4.2.5 on 2023-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("robots", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="robot", name="model", field=models.CharField(max_length=2)),
        migrations.AlterField(
            model_name="robot", name="serial", field=models.CharField(blank=True, max_length=5, null=True)
        ),
        migrations.AlterField(model_name="robot", name="version", field=models.CharField(max_length=2)),
    ]
